DROP TABLE IF EXISTS links CASCADE;

CREATE TABLE links (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  vote_url VARCHAR(255) NOT NULL,
  result_url VARCHAR(255) NOT NULL
);
